# Generated by Django 5.0.1 on 2024-01-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appt_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_first_name', models.CharField(max_length=100)),
                ('client_last_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=15)),
                ('client_email', models.EmailField(max_length=254)),
                ('appt_date', models.DateField()),
                ('appt_time', models.TimeField()),
            ],
        ),
    ]
